# Generated by Django 5.2.7 on 2025-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Usu_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('Usu_email', models.CharField(blank=True, max_length=60, null=True)),
                ('Usu_telefono', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
    ]
