# Generated by Django 5.2.7 on 2025-10-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Usu_contraseña',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
