# Generated by Django 5.2.7 on 2025-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_usuario_usu_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
