# Generated by Django 5.2.7 on 2025-10-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='conversionmonto',
            name='factor_usado',
        ),
        migrations.RemoveField(
            model_name='conversionmonto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='emisor',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='factorconversion',
            name='moneda_destino',
        ),
        migrations.RemoveField(
            model_name='factorconversion',
            name='moneda_origen',
        ),
        migrations.RemoveField(
            model_name='factorconversion',
            name='pais',
        ),
        migrations.DeleteModel(
            name='BitacoraCambios',
        ),
        migrations.DeleteModel(
            name='CalificacionTributaria',
        ),
        migrations.DeleteModel(
            name='ConversionMonto',
        ),
        migrations.DeleteModel(
            name='Emisor',
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
        migrations.DeleteModel(
            name='FactorConversion',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
