# Generated by Django 5.2.7 on 2025-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_delete_tasadecambio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciontributaria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='calificaciontributaria',
            name='tasa_o_factor',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
