# Generated by Django 5.2.7 on 2025-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_calificaciontributaria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo_contribuyente', models.CharField(help_text='Ej: Persona Natural, Persona Jurídica', max_length=50)),
                ('actividad_economica', models.CharField(help_text='Ej: Comercio al por menor, Servicios...', max_length=200)),
                ('codigo_actividad', models.CharField(blank=True, help_text='Código,si aplica', max_length=20, null=True)),
                ('regimen_tributario', models.CharField(help_text='Ej: Pro Pyme, Renta Presunta', max_length=120)),
                ('impuestos_aplicables', models.CharField(help_text='Ej: IVA, Impuesto a la Renta', max_length=255)),
                ('obligaciones_formales', models.CharField(help_text='Ej: DJ, F29, F22', max_length=255)),
                ('jurisdiccion', models.CharField(help_text='Ej: Santiago, Lima o Bogota', max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='CalificacionTributaria',
        ),
    ]
