# Generated by Django 5.2.7 on 2025-10-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_clasificaciontributaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClasificacionTributaria',
        ),
    ]
