# Generated by Django 5.2.7 on 2025-10-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_clasificaciontributaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClasificacionTributaria',
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
