# Generated by Django 5.2.7 on 2025-10-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_delete_clasificaciontributaria_delete_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial (ej: Peso Chileno)', max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Código ISO (ej: CLP)', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_iso', models.CharField(help_text='Código ISO (ej: CHL)', max_length=3, unique=True)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.moneda')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la calificación (ej: IVA General)', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tasa_o_factor', models.DecimalField(decimal_places=5, help_text='El valor numérico de la tasa (ej: 0.19 para 19%)', max_digits=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_destino', to='miapp.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_origen', to='miapp.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'unique_together': {('moneda_origen', 'moneda_destino')},
            },
        ),
    ]
